#!/bin/sh
# isfar piston tanks control script
if [ "$#" -ne 2 ]; then
	    echo "Give 2 arguments..."
		exit -1
fi

if [ "$1" != "-" ]; then
	s 0x09 0x06 $1
fi

if [ "$2" != "-" ]; then
	s 0x0a 0x06 $2
fi
